structure(list(method = "GET", url = "https://data.geopf.fr/geocodage/search?q=1%20Place%20Georges%20Freche&autocomplete=0&index=address&limit=5&type=housenumber&category=&postcode=&city=Montpellier&lon=&lat=", 
    status_code = 200L, headers = structure(list(date = "Wed, 12 Feb 2025 07:49:48 GMT", 
        `set-cookie` = "REDACTED", `content-type` = "application/json; charset=utf-8", 
        vary = "Origin", etag = "W/\"1fd-gmOLnqW7Xk7A+acYQ3DknA0vFZI\"", 
        `content-encoding` = "gzip", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
        `access-control-allow-origin` = "*", `access-control-allow-credentials` = "true", 
        `access-control-allow-methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `access-control-allow-headers` = "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Content-Disposition,Content-Length,X-Community", 
        `access-control-max-age` = "1728000", `transfer-encoding` = "chunked", 
        `x-iplb-request-id` = "5D184490:C36E_91EFC1E7:01BB_67AC529C_7382739:3099", 
        `x-iplb-instance` = "61218"), class = "httr2_headers"), 
    body = charToRaw("{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[3.896549,43.598842]},\"properties\":{\"label\":\"1 Place Georges Frêche 34070 Montpellier\",\"score\":0.9723590909090909,\"housenumber\":\"1\",\"id\":\"34172_2388_00001\",\"name\":\"1 Place Georges Frêche\",\"postcode\":\"34070\",\"citycode\":\"34172\",\"x\":772413.38,\"y\":6278165.21,\"city\":\"Montpellier\",\"context\":\"34, Hérault, Occitanie\",\"type\":\"housenumber\",\"importance\":0.69595,\"street\":\"Place Georges Frêche\",\"_type\":\"address\"}}]}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
